backend:
  name: git-gateway
  branch: master
publish_mode: editorial_workflow
media_folder: "static/images/uploads"
public_folder: "/images/uploads"
collections:
  - name: "blog"
    label: "t-tajiri blog"
    folder: "content/blog"
    create: true
    slug: "{{ slug }}"
    sort: "date:desc"
    fields:
      - {label: "Title", name: "title", widget: "string", required: true}
      - {label: "Publish Date", name: "date", widget: "date", required: true}
      - {label: "Updated Date", name: "update", widget: "date", required: false}
      - {label: "Body", name: "body", widget: "markdown", required: true}
