# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14.x'

    - run: yarn install

    - run: yarn test

    - name: Archive coverage results
      uses: actions/upload-artifact@v1
      with:
        name: coverage-report
        path: coverage

  staticAnalysis:
    needs: build
    name: static analysis
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v2

      - name: Download coverage results
        uses: actions/download-artifact@v1
        with:
          name: coverage-report
          path: coverage

      - name: fix code coverage paths
        working-directory: ./coverage
        run:
          sed -i 's/\/home\/runner\/work\/blog\/blog\/coverage\//\/github\/workspace\//g' lcov.info

      - name: analysis with SonarCloud
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  measurePage:
    needs: staticAnalysis
    name: measuring page performance
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'

      - run: yarn install

      - name: yarn measure
        run: yarn measure
        id: measure

      - name: output results
        run: echo "The time was ${{ steps.measure.outputs.time }}"
